title: Zoe Catherine Rudnick
email: zrudnic1@jh.edu
description: >-
  Biomedical Engineering PhD student working on computational genomics software.
  Second year student in the Pertea Lab.
baseurl: ""
url: "https://zrudnick.github.io"
github_username: zrudnick
linkedin_username: zoe-rudnick

# Build settings
markdown: kramdown
theme: slate
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections for organizing content
collections:
  projects:
    output: true
    permalink: /:collection/:name/
