title: Zoe Catherine Rudnick
email: zrudnic1@jh.edu
description: >-
  Biomedical Engineering PhD student working on computational genomics software.
  Second year student in the Pertea Lab.
baseurl: ""
url: "https://zrudnick.github.io"
github_username: zrudnick
linkedin_username: zoe-rudnick

# Build settings
markdown: kramdown
theme: minima
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Sass
sass:
  style: compressed

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
