title: Zoe Catherine Rudnick
email: zrudnic1@jh.edu
description: >-
  Biomedical Engineering PhD student working on algorithms for computational biology. Pertea Lab.
baseurl: ""
url: "https://zrudnick.github.io"
github_username: zrudnick
linkedin_username: zrudnick

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections for organizing content
collections:
  projects:
    output: true
    permalink: /:collection/:name/
